;******************************************
;*
;* Default startup.ts for TreeSync
;*
;******************************************

; Exclude some common files that don't need to be copied
exclude file = "Thumbs.db"
exclude file = "desktop.ini"
;
; Don't copy CVS directories, as they will be incorrect
; on most machines
exclude dir = "CVS"
;
; Exlude copying the intermediate files from the compiler
exclude ext = ".obj"
exclude ext = ".pdb"
;
; Exclude copying backup files generated by Eagle
exclude ext = ".s#1"
exclude ext = ".s#2"
exclude ext = ".s#3"
exclude ext = ".s#4"
exclude ext = ".s#5"
exclude ext = ".s#6"
exclude ext = ".s#7"
exclude ext = ".s#8"
exclude ext = ".s#9"
exclude ext = ".b#1"
exclude ext = ".b#2"
exclude ext = ".b#3"
exclude ext = ".b#4"
exclude ext = ".b#5"
exclude ext = ".b#6"
exclude ext = ".b#7"
exclude ext = ".b#8"
exclude ext = ".b#9"
;
; Print file copy and directory creation by default
opt = pf,pd

;******************************************
